name: Integrate PR Content with ChatGPT

on:
  pull_request:
    branches:
      - master

jobs:
  interact-with-chatgpt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure the whole repo history is pulled

      - name: Extract PR Content
        run: |
          git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge
          git checkout FETCH_HEAD
          files_changed=$(git diff --name-only ${{ github.event.pull_request.base.sha }} HEAD)
          changes=""
          for file in $files_changed; do
            diff=$(git diff ${{ github.event.pull_request.base.sha }} HEAD -- $file)
            changes+="${file}:\n${diff}\n"
          done
          # Encode changes to base64 to ensure safe transmission
          encoded_changes=$(echo -n "$changes" | base64 -w 0)
          echo "ENCODED_CHANGES=${encoded_changes}" >> $GITHUB_ENV

      - name: Call ChatGPT with PR content
        run: |
          # Decode base64 changes to normal text (for debugging or if needed)
          decoded_changes=$(echo "${{ env.ENCODED_CHANGES }}" | base64 --decode)
          response=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -d '{
                    "model": "gpt-4o-mini",
                    "store": true,
                    "messages": [
                        {"role": "user", "content": "'"$decoded_changes"'"}
                    ]
                }')
          echo "Response from ChatGPT: $response"
