name: Integrate PR Content with ChatGPT

on:
  pull_request:
    branches:
      - master

jobs:
  interact-with-chatgpt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure the whole repo history is pulled

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Extract PR Content
        run: |
          # Fetching the merge reference of the PR
          git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge
          git checkout FETCH_HEAD
          # Extracting PR description
          pr_description="${{ github.event.pull_request.body }}"
          echo "Extracted PR Description: $pr_description"
          echo "PR_DESCRIPTION<<EOF" >> $GITHUB_ENV
          echo "$pr_description" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Prepare PR Content for JSON
        run: |
          # Escape special characters to make the string JSON-safe
          json_pr_description=$(echo "$PR_DESCRIPTION" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g' | awk '{printf "%s\\n", $0}')
          echo "Formatted PR Description for JSON: $json_pr_description"
          echo "JSON_SAFE_PR_DESCRIPTION<<EOF" >> $GITHUB_ENV
          echo "$json_pr_description" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Call ChatGPT with PR content
        run: |
          response=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -d '{
                    "model": "gpt-4o-mini",
                    "store": true,
                    "messages": [
                        {"role": "user", "content": "'"Faca um code review desse codigo, seja breve e aponte melhorias${{ env.JSON_SAFE_PR_DESCRIPTION }}"'"} 
                    ]
                }')
          echo "Response from ChatGPT: $response"
